// <auto-generated />
namespace Seguetech.Zippy.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RepurposeCanonicalFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RepurposeCanonicalFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201506252041095_RepurposeCanonicalFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
