// <auto-generated />
namespace Seguetech.Zippy.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddMedicationManufacturer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMedicationManufacturer));
        
        string IMigrationMetadata.Id
        {
            get { return "201506251853284_AddMedicationManufacturer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
